### ISSUE TITLE
RoundedCube should be centered by default

### ISSUE THREAD

**Issue by mikosik** [miho/JCSG#22]
`RoundedCube` class has private field `centered` which gets `false` value during initialization as there's no explicit initialization of that field. The whole functionality that is controlled by that flag field looks to me like copy pasted from `Cube` class with the only difference that in `Cube` class it is explicitly initialized with `true` value. This copy-paste mistake makes it impossible to control `centered` field in `RoundedCube` as the only method the changes its value (`noCenter()`) changes it to `false` so there's no possibility to change it to true.

**Comment by madhephaestus** [comment]
This issue is resolved in the branch: https://github.com/NeuronRobotics/JCSG

**Comment by miho** [comment]
Thanks for the fix. I'll add the fix to the master branch.
