### ISSUE TITLE
Text3D Depends on a specific version of JCSG

### ISSUE THREAD

**Issue by madhephaestus** [miho/JCSG#31]
JCSG depends on extfxyz, which in turn dependes on JCSG 0.3.2, causing a dependency loop and importing out of date classes. This breaks downstream implementations. 

https://repo1.maven.org/maven2/eu/mihosoft/ext/org/fxyz/extfxyz/0.4/extfxyz-0.4.pom

If they both depend on each other, maybe they should be merged?

**Comment by miho** [comment]
extfxyz is just a workaround.

> If they both depend on each other, maybe they should be merged?

Unfortunately, they are separate projects. I'm not the author of the FXyz library. It just has been published via bintray by the main authors. Maybe you could ask them to split the library. This would break the loop.

**Comment by madhephaestus** [comment]
I fixed my Implementation of 3d test with no external dependencies. Would you be interested in a PR to replace the underlying system?

**Comment by madhephaestus** [comment]
If this PR gets merged, i will work from that branch to add the bezier functionality in the same way.
