### ISSUE TITLE
Text3d support

### ISSUE THREAD

**Issue by davydov-vyacheslav** [miho/JCSG#43]
Hi,

Why existing mechanism of displaying 3d text was commented (during refactoring?) ? Is is possible to return it back?

Thanks,
Slava

**Comment by miho** [comment]
The current implementation caused some problems. It will reappear eventually. We will most probably create a separate project, e.g., JCSG-Text to solve some of the circular dependency problems. At the moment it is not high priority though.

**Comment by davydov-vyacheslav** [comment]
:( just wondering, whether there is a way for workaround to display the 3d text (actually, but main task it to subtract 3d text from object) ?

**Comment by madhephaestus** [comment]
My fork supports text3d and a bunch of additional primitives, cad operations and extrusion procedures:

https://github.com/NeuronRobotics/JCSG

Replace the gradle line with:

compile "com.neuronrobotics:JavaCad:0.10.1"

Here is the API documentation: http://commonwealthrobotics.com/JavaCAD/Overview/

**Comment by davydov-vyacheslav** [comment]
@madhephaestus thank you so much!
