### ISSUE TITLE
How to import OBJ ?

### ISSUE THREAD

**Issue by solub** [miho/JCSG#56]
Thank you for this wonderful library @miho .

I'm testing the different functions of JCSG and would like to know how to import an OBJ file.

Writing `MyObj = Importer3D.load("column.obj")` returns the following error:

> Unknown 3D file format [obj] at eu.mihosoft.jcsg.ext.openjfx.importers.Importer3D.loadIncludingAnimation(Importer3D.java:139)

Another attempt with `MyObj= ObjImporter("C:/Users/solub/Desktop/meshes/column.obj")` returns:

> java.net.MalformedURLException: unknown protocol: c
> 	at java.net.URL.<init>(URL.java:600)
> 	at java.net.URL.<init>(URL.java:490)
> 	at java.net.URL.<init>(URL.java:439)
> 	at eu.mihosoft.jcsg.ext.openjfx.importers.obj.ObjImporter.<init>(ObjImporter.java:108)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

Am I doing something wrong here ?

**Comment by solub** [comment]
@miho Any help on this matter would also be greatly appreciated.

Please.

**Comment by miho** [comment]
There's no OBJ importer. Only exporting is supported (see project description). You can import STL files, however.

**Comment by elect86** [comment]
let me suggest [this jvm port](https://github.com/kotlin-graphics/assimp) of assimp

**Comment by miho** [comment]
Good suggestion. With that you can "add support" for all formats supported by assimp. If you are okay with going through this intermediate step you can achieve this with only a few lines of code.

**Comment by solub** [comment]
Thanks to both of you.

Now that miho clarified that there is no OBJ importer I realize my question was irrelevant. Apologies.

Processing has a built-in mesh importer that I can use. Unfortunately, it seems impossible to convert the imported shape to a CSG object.
