### ISSUE TITLE
Creating a Polygon

### ISSUE THREAD

**Issue by solub** [miho/JCSG#57]
Hi,

I am unable to reproduce the following example (found [here](https://stackoverflow.com/questions/54891421/how-to-create-a-polygon-with-jcsg))  

```
List<Vector3d> vertices = new ArrayList<>();

vertices.add(Vector3d.xyz(0, 0, 0));
vertices.add(Vector3d.xyz(50, 25, 0));
vertices.add(Vector3d.xyz(100, 0, 0));
vertices.add(Vector3d.xyz(0, 100, 0));

List<Polygon> t = Polygon.fromConcavePoints(vertices);
CSG csg = CSG.fromPolygons(t);
```

All I get is this error:

> This static method of interface Vector3d can only be accessed as Vector3d.xyz

Again, I might be doing something wrong and would really appreciate some help.

Respectfully

**Comment by miho** [comment]
Since this is a compilation error we need to know the Java version you are using.

**Comment by solub** [comment]
Thank you for the reply.

To be more specific, I am loading JCSG in Processing (example sketch provided [here](https://stackoverflow.com/questions/56999816/is-it-possible-to-use-jcsg-library-with-processing)), which, I think, is using Java 8. Would that be a problem ?

**Comment by solub** [comment]
@miho  Any help would be appreciated. Please tell me if you need more information regarding this issue.

**Comment by miho** [comment]
Have you tried with standard Java 8? I can't reproduce this behavior. So I assume it is Processing related.

**Comment by solub** [comment]
Alright, thank you for the feedback. I'll try to figure this out with the Processing guys.
